import React from 'react';
import Head from 'next/head';
import { Container } from '@chakra-ui/react';
import Navbar from './Navbar';

const { NEXT_PUBLIC_GOOGLE_MAPS_API_KEY } = process.env;

function SiteLayout({ children }) {
  return (
    <React.Fragment>
      <Head>
        <title>The Path</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src={`https://maps.googleapis.com/maps/api/js?key=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
        ></script>
      </Head>
      <Navbar />
      <Container maxW="7xl">{children}</Container>
    </React.Fragment>
  );
}

export default SiteLayout;
