import React from 'react';
import Head from 'next/head';
import { Container, Flex } from '@chakra-ui/react';
import Navbar from './Navbar';
import Footer from './Footer';

function SiteLayout({ children }) {
  return (
    <React.Fragment>
      <Head>
        <title>The Path</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" minH="100vh">
        <Navbar />
        <Container maxW="7xl" mb={8}>
          {children}
        </Container>
        <Footer mt={'auto'} />
      </Flex>
    </React.Fragment>
  );
}

export default SiteLayout;
