import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>The Path</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </React.Fragment>
  );
};

export default Home;
